### ISSUE TITLE
机选一注

### ISSUE THREAD

**Issue by kalashnlkov** [bd4sur/HackRF-Lottery#1]
三号无证游民Freshman，等证验机中，鉴于这个账户还不是那么实名上网，操作证ID不在此记录。

最大的需求可能是模拟各种调制吧，虽然GNU Radio应该也可做到，但是通过实物发射来学习的内驱力还是更大一些。
P.S. 据说40m上东欧人民经常在频谱图上发图论战，但是从没见过。

目前仅有一RTL-SDR、一手台以及自焊pixie CW收发信机一只。

语言组织能力稀烂，望见者海涵……

**Comment by bd4sur** [comment]
抄收了老朋友，爱好者身份已经个别沟通确认过了，给您加入抽奖名单，73！
