### ISSUE TITLE
给我也整一个

### ISSUE THREAD

**Issue by Pichuworks** [bd4sur/HackRF-Lottery#2]
本人是B证业余无线电爱好者，呼号BD4RCW。
只玩过电视棒的我也想搞个大玩具，然后给母校社团也玩玩【

**Comment by Pichuworks** [comment]
另外我是@橘猫**

**Comment by bd4sur** [comment]
抄收了，您也是老朋友了，给学校社团玩再好不过了，给您加入抽奖名单，73！
