### ISSUE TITLE
来抽一个

### ISSUE THREAD

**Issue by Po84210** [bd4sur/HackRF-Lottery#4]
本人是持证业余无线电爱好者，本人负责的集体台呼号 BY4WNG。
目前社团里的 SDR 设备仅有 R820T2，还没有能发射的 SDR 设备，想尝试配合 GNU Radio 实现点高阶调制玩玩。

**Comment by bd4sur** [comment]
抄收了，老朋友，相当熟悉了，给您加入抽奖名单。话说学院层面应该不缺USRP这样的高级玩具呀，只是用电视棒的话，对东大集体台这样的知名电台来说还是有点那啥了（

总之祝好运~以后有什么新玩法，还请指教，73！
